<a href="https://colab.research.google.com/github/itforankit/GenerativeAI/blob/main/NN_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#!pip install tensorflow

In [2]:
import tensorflow as tf
from tensorflow import keras

In [3]:
mnist = keras.datasets.mnist

In [4]:
(X_train, Y_train), (X_test, Y_test) =mnist.load_data()

In [5]:
X_train[2]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,  67, 232,  39,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,  62,  81,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0, 120, 180,  39,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 126, 163,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   2, 153, 210,  40,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 220, 163,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,  27, 254, 162,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 222, 163,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0, 183, 254, 125,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,  46, 245, 163,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0, 198, 254,  56,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0, 120, 254, 163,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,  23, 231, 254,  29,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0, 159, 254, 120,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0, 163, 254, 216,  16,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0, 159, 254,  67,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  14,  86, 178, 248, 254,  91,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0, 159, 254,  85,   0,   0,   0,  47,  49, 116, 144,
        150, 241, 243, 234, 179, 241, 252,  40,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0, 150, 253, 237, 207, 207, 207, 253, 254, 250, 240,
        198, 143,  91,  28,   5, 233, 250,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 119, 177, 177, 177, 177, 177,  98,  56,   0,
          0,   0,   0,   0, 102, 254, 220,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 169, 254, 137,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 169, 254,  57,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 169, 254,  57,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 169, 255,  94,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 169, 254,  96,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 169, 254, 153,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 169, 255, 153,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   

In [6]:
RESHAPE=784
X_train = X_train.reshape(60000,RESHAPE)
X_test = X_test.reshape(10000,RESHAPE)

In [7]:
X_train.shape

(60000, 784)

In [8]:
X_test.shape

(10000, 784)

In [9]:
X_train.astype('float')
X_test.astype('float')

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [10]:
X_train=X_train/255
X_test =X_test/255

In [11]:
X_train[2]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [12]:
Y_train = tf.keras.utils.to_categorical(Y_train,10)
Y_test = tf.keras.utils.to_categorical(Y_test,10)

In [13]:
Y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

design the model
define the architecure of the model

Sequential Model -> 1 hidden layer
stack of layers

In [14]:
model = tf.keras.Sequential()

In [15]:
# 1 hidden layer 64 neuorns
noofhidden=64
model.add(tf.keras.layers.Dense(noofhidden, activation='relu'))

# 2nd hidden layer will have 30 neuorns
model.add(tf.keras.layers.Dense(30, activation='relu'))

In [16]:
#addd output layer with 10 output units/neuorns
model.add(tf.keras.layers.Dense(10, activation='softmax'))

In [19]:
#compiling the model
import keras.losses
model.compile(loss='categorical_crossentropy', metrics=['accuracy'])

In [20]:
#train the model
#60000/64=938
model.fit(X_train, Y_train, batch_size=64, epochs=50)

Epoch 1/50
938/938 [==============================] - 6s 4ms/step - loss: 0.3343 - accuracy: 0.9067
Epoch 2/50
938/938 [==============================] - 3s 3ms/step - loss: 0.1611 - accuracy: 0.9530
Epoch 3/50
938/938 [==============================] - 3s 3ms/step - loss: 0.1200 - accuracy: 0.9650
Epoch 4/50
938/938 [==============================] - 3s 3ms/step - loss: 0.0983 - accuracy: 0.9704
Epoch 5/50
938/938 [==============================] - 4s 4ms/step - loss: 0.0836 - accuracy: 0.9747
Epoch 6/50
938/938 [==============================] - 3s 3ms/step - loss: 0.0716 - accuracy: 0.9780
Epoch 7/50
938/938 [==============================] - 3s 3ms/step - loss: 0.0622 - accuracy: 0.9815
Epoch 8/50
938/938 [==============================] - 3s 3ms/step - loss: 0.0555 - accuracy: 0.9833
Epoch 9/50
938/938 [==============================] - 4s 4ms/step - loss: 0.0488 - accuracy: 0.9851
Epoch 10/50
938/938 [==============================] - 3s 3ms/step - loss: 0.0442 - accuracy: 0.9865

In [21]:
model.evaluate(X_test,Y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.2118 - accuracy: 0.9747


[0.21182726323604584, 0.9746999740600586]

In [22]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(784, 64) dtype=float32, numpy=
 array([[ 0.01366948,  0.07678332,  0.00711576, ..., -0.05303409,
          0.0134164 ,  0.02169444],
        [ 0.04895867,  0.07342158,  0.07131123, ...,  0.06912427,
          0.07597687, -0.08057794],
        [ 0.06763209, -0.0815082 , -0.06691994, ...,  0.07861542,
         -0.00853629, -0.08260219],
        ...,
        [ 0.00763319, -0.03296028,  0.03528656, ..., -0.07965227,
         -0.04841175,  0.0049275 ],
        [ 0.05108876, -0.03403867, -0.01550101, ..., -0.04371716,
          0.00860685,  0.04541405],
        [-0.04518052, -0.05714482, -0.05850423, ..., -0.05819174,
         -0.04556838,  0.0588512 ]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(64,) dtype=float32, numpy=
 array([ 0.06044283,  0.22393   , -0.21993653, -0.0625051 , -0.01925567,
         0.05170344, -0.03117982, -0.07931014,  0.02647083, -0.05281538,
        -0.02377425,  0.14870127, -0.51033247, -0.24435385,  0.01548731,
      